### ISSUE TITLE
Use WalletProvider without fallback

### ISSUE THREAD

**Issue by midgerate** [kesne/ethereal-react#42]
Hey!! Awesome library. I was thinking of doing something like this but looks like I will be using this library. 

I wanted to display my webpage without needed to connect to wallet and it seems that I am unable to use WalletProvider without a fallback. 

I tried to use my webpage router as a fallback but then I cannot find a hook that tells me if the wallet is connected or not which I could use to render the connect wallet button.

**Comment by midgerate** [comment]
@kesne Thanks for your reply. 

Basically all the data that I am supposed to get from hooks if they require a connected wallet provider, should return undefined 

`const address = useUserAddress()` should return undefined if wallet is not connected. If wallet is connected, it returns the address. 

I had a feeling that this might be the reason why you forced a fallback, but majorly of the dapps want people to explore the whole app, before users decide to connect their wallet. 

I see a lot of potential in the project, and I would love to contribute to it as well. :) 

Do you think its easy to remove or make fallback optional with the current setup? I'd like to use this library in one of my projects and I know this library does a lot of extra legwork that I would have to do myself.

**Comment by kesne** [comment]
Yeah I was planning on doing all 3, just wanted to make sure it addressed your needs!

I'll probably get around to this in the next day.

**Comment by kesne** [comment]
The second and third points have been implemented, so you can now specify `noFallback` on the walletprovider and it will no longer trigger the fallback when it is not connected. I need to write docs for this pattern still, but it should be possible to use now.
